databases:
    - name: x-disk
      plan: free

services:
    - type: web
      name: rails
      env: node
      runtime: ruby
      buildCommand: "./bin/render-build.sh"
      startCommand: "bundle exec rails s" && "bin/webpack"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: x-disk
                property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false
      plan: free
